#!/usr/bin/env node
/**
 * Populate noor-data from TarteelAI/quran-assets (public).
 *
 *   - tafsir/   : English tafsir JSON (as-is; staging for the tafsir feature).
 *   - indopak/  : per-word IndoPak Arabic text (as-is; staging for IndoPak).
 *
 * Translations are built by scripts/fetch-translations.mjs (all tanzil sets +
 * the catalog manifest). Word-by-word (en_wbw.json) is generated by the Noor
 * repo's scripts/build-wbw.mjs — see word-by-word/README.md.
 *
 * Usage:  node scripts/fetch-data.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = 'https://raw.githubusercontent.com/TarteelAI/quran-assets/main';
const CONCURRENCY = 12;

// Shipped: en-tafsir-mokhtasar (explicit free license) + the two classical Arabic
// tafsirs below (public domain). ar-tafsir-qurtubi = Al-Qurtubi (d. 1273),
// ar-tafsir-baghawy = Al-Baghawi / Ma'alim al-Tanzil (d. 1122).
// NOTE: quran-assets' "ar-tafsir-tanweer" is Ibn Ashur's at-Tahrir wa't-Tanwir
// (d. 1973) — modern/copyrighted, NOT the classical Tanwir al-Miqbas — so it is
// intentionally excluded. The two English files below are inputs for the
// gitignored (copyright-risk) wire files; not shipped.
const TAFSIRS = [
  'en-tafsir-mokhtasar',
  'ar-tafsir-qurtubi',
  'ar-tafsir-baghawy',
  'en-tafsir-ibn-kathir',
  'en-tafsir-maarif-ul-quran',
];

async function getJson(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status}`);
  return r.json();
}
const ensureDir = (d) => mkdir(d, { recursive: true });

async function buildTafsir() {
  await ensureDir(resolve(ROOT, 'tafsir'));
  for (const name of TAFSIRS) {
    try {
      const data = await getJson(`${SRC}/tafsir/${name}.json`);
      await writeFile(resolve(ROOT, 'tafsir', `${name}.json`), JSON.stringify(data));
      console.log(`✓ tafsir/${name}.json`);
    } catch (e) {
      console.warn(`! ${name}: ${e.message}`);
    }
  }
}

async function buildIndopak() {
  await ensureDir(resolve(ROOT, 'indopak'));
  const tasks = [];
  for (let s = 1; s <= 114; s++) {
    tasks.push(async () => {
      const data = await getJson(`${SRC}/indopak-word-by-word/${s}.json`);
      await writeFile(resolve(ROOT, 'indopak', `${s}.json`), JSON.stringify(data));
    });
  }
  let i = 0;
  let ok = 0;
  let fail = 0;
  await Promise.all(
    Array.from({ length: CONCURRENCY }, async () => {
      while (i < tasks.length) {
        const idx = i++;
        try {
          await tasks[idx]();
          ok++;
        } catch (e) {
          fail++;
          console.warn(`! indopak ${idx + 1}: ${e.message}`);
        }
      }
    })
  );
  console.log(`✓ indopak/ ${ok}/114${fail ? ` (${fail} failed)` : ''}`);
}

const t0 = Date.now();
console.log('Populating noor-data (tafsir + indopak) from quran-assets…');
await buildTafsir();
await buildIndopak();
console.log(`done in ${((Date.now() - t0) / 1000).toFixed(1)}s`);
